### ISSUE TITLE
下载了以后 不可运行

### ISSUE THREAD

**Issue by coderAs7** [ISCSMobileOrg/SANetwork#2]

**Comment by ISCS-iOS** [comment]
下载之后 cd 到工程目录下 执行 pod install

**Comment by coderAs7** [comment]
不是缺少第三方框架的问题哦,是MJRefersh出问题了,后来我把cocoapods整个进行了移除,然后重新pod install 就好了

**Comment by coderAs7** [comment]
感谢分享如此优秀的代码

**Comment by ISCS-iOS** [comment]
没有时间去整理详细的测试案例，在使用时，有什么问题，你可以联系我们
